language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: stefanitsky
  password:
    secure: JA41R1qaEhdTWRkTuPvo2c4y4p54zrOHCYFGyxpCKJc10/NJyl0tD5iM7qJ8yYxldL2V0DzSstCgsQ2x3MZCH+JiktxWpLWq2FIoYnkpNnkCb0/81xk1V4/cXCXLqb8+4QBzccgYfnSMBMyKvIT/j6KgXGNVRj3YY8HDvCrF77Cb+fGI9bpHRhF9ZNE43IFgxBwenJzKiHe1lM287vIcoYZkZrDC0yEWBLROtnDfQprOuCIwnBmWujtgBnIGrAc7MiDwlzLygBAiG88seqJYq5R07LqI7r9lBf5sTSSlMvlk8V0TS8llJ8Ybh8dgAkMRqM/hlTAFJ+wyed/VUiaAcN10mBLtz0KdENQljf/fKBjcyxvmD3Q1UkhGXf+B+xOLud5eO4WnDF0b1xcY8dYFv37pTcbiZ+kn7CsaZWdNhxVCk1Em6XFZhkMovP2N+nBUunwa+0oDAelOeCz5SX/wksZSz6PCJdlaAjA3QRVtItw7ESXXccogU24pgTm0LOXT5wZJZbWX6fLKvgdrGAyRZDMeMJXQl16jLzFFmTZaDLJ8dz2TwhF/hDB/A5n+PAT+O9b11MzWN59vkir0Lhupix5kYgohe48DmzyGIbkCsAXwHywatR2z23+leHw31qVCqP/Lb/EdGTKUj+3lSKT58h2pQ8RbECBmLsWqv9ouESA=
  on:
    tags: true
    repo: stefanitsky/yandex_market_language
    python: 3.8
