language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis coverage codecov faker
script:
    - tox
    - coverage run --source yandex_market_language -m pytest
after_success: codecov
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: "__token__"
  password:
    secure: lEVFETUH0hmh8z4aNwo6iDKNMncISsBaF3fV8w62e6qZ2t7l4Uxla3NQHjoX3gS2hq/2PWMXkQrpxAswaLn7pxI3tzH8qp6t1RzNygCA34s509URp2u+Y0/CYKv3NVgPbrlqj2zSgHcjApFwL9Ev+veQ40Xc9gWgMyYeZy2KWVwW+U5lcKKH+UfDZflil7BW+CSK3MfeJb33lBju/mopkQ4ex6tSYQnr5LBzkhXw7tL5uXbPjbcURHtiS0cS8dRpBJCvg7EA+ZaVmBKI9lMOj6e4c/Da8p0oKZHc2itzxISxvjaFuRJMV2swhp+SVusfqXN+1lSxAvaMZ2buKJGOdWdDXPrzNpTaGzK9fb6GSeKofOyZ5Aqn4PQH2Sr+Bu/wPi2kJHfc3h4/5PIKmVxjD3sPJKetV5WZ8XupcwXsqakgGC4TDcnS+RfqlR9nUfta0FoIZRFJ3azwoUoL+KrkVMorpyxBwAR+6HCWwwiyS1eYTMR7FXofaHJysKNTOqxF1bzv94n6qyUIwphoEWwb/gujVeZIw/bA4uQyJNVMP2nVImqbwnYAhFHpG+lYwH2kan10iM+D+FAQ09H+0nG6RbOdZk6HJ48Ta8ZqX2zY58UUBDln6zXT5urzANdZ6E8dQokmv/UJgzh2a4mZZlKp85C/2pDYrJTeBYctP32VqFU=
  on:
    tags: true
    repo: stefanitsky/yandex_market_language
    python: 3.8
